// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: lab5.proto

package Broker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kais_Broker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *Kais_Broker) Reset() {
	*x = Kais_Broker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kais_Broker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kais_Broker) ProtoMessage() {}

func (x *Kais_Broker) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kais_Broker.ProtoReflect.Descriptor instead.
func (*Kais_Broker) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{0}
}

func (x *Kais_Broker) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Kais_Broker) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type Broker_Kais struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direccion string `protobuf:"bytes,1,opt,name=direccion,proto3" json:"direccion,omitempty"`
}

func (x *Broker_Kais) Reset() {
	*x = Broker_Kais{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broker_Kais) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker_Kais) ProtoMessage() {}

func (x *Broker_Kais) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker_Kais.ProtoReflect.Descriptor instead.
func (*Broker_Kais) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{1}
}

func (x *Broker_Kais) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type Kais_Fulcrum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *Kais_Fulcrum) Reset() {
	*x = Kais_Fulcrum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kais_Fulcrum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kais_Fulcrum) ProtoMessage() {}

func (x *Kais_Fulcrum) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kais_Fulcrum.ProtoReflect.Descriptor instead.
func (*Kais_Fulcrum) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{2}
}

func (x *Kais_Fulcrum) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Kais_Fulcrum) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type Fulcrum_Kais struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CantEnemigos int32  `protobuf:"varint,1,opt,name=cant_enemigos,json=cantEnemigos,proto3" json:"cant_enemigos,omitempty"`
	Reloj        string `protobuf:"bytes,2,opt,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *Fulcrum_Kais) Reset() {
	*x = Fulcrum_Kais{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fulcrum_Kais) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulcrum_Kais) ProtoMessage() {}

func (x *Fulcrum_Kais) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulcrum_Kais.ProtoReflect.Descriptor instead.
func (*Fulcrum_Kais) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{3}
}

func (x *Fulcrum_Kais) GetCantEnemigos() int32 {
	if x != nil {
		return x.CantEnemigos
	}
	return 0
}

func (x *Fulcrum_Kais) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

type Ing_Broker_AgregarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Valor  int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *Ing_Broker_AgregarBase) Reset() {
	*x = Ing_Broker_AgregarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Broker_AgregarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Broker_AgregarBase) ProtoMessage() {}

func (x *Ing_Broker_AgregarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Broker_AgregarBase.ProtoReflect.Descriptor instead.
func (*Ing_Broker_AgregarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{4}
}

func (x *Ing_Broker_AgregarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Broker_AgregarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Broker_AgregarBase) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

// Este mensaje sirve para todas las comunicaciones Broker-Ingeniero
type Broker_Ing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direccion string `protobuf:"bytes,1,opt,name=direccion,proto3" json:"direccion,omitempty"`
}

func (x *Broker_Ing) Reset() {
	*x = Broker_Ing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broker_Ing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker_Ing) ProtoMessage() {}

func (x *Broker_Ing) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker_Ing.ProtoReflect.Descriptor instead.
func (*Broker_Ing) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{5}
}

func (x *Broker_Ing) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type Ing_Fulcrum_AgregarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Valor  int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *Ing_Fulcrum_AgregarBase) Reset() {
	*x = Ing_Fulcrum_AgregarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Fulcrum_AgregarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Fulcrum_AgregarBase) ProtoMessage() {}

func (x *Ing_Fulcrum_AgregarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Fulcrum_AgregarBase.ProtoReflect.Descriptor instead.
func (*Ing_Fulcrum_AgregarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{6}
}

func (x *Ing_Fulcrum_AgregarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Fulcrum_AgregarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Fulcrum_AgregarBase) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

// Este mensaje sirve para todas las comunicaciones Fulcrum-Ingeniero
type Fulcrum_Ing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reloj string `protobuf:"bytes,1,opt,name=reloj,proto3" json:"reloj,omitempty"`
}

func (x *Fulcrum_Ing) Reset() {
	*x = Fulcrum_Ing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fulcrum_Ing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulcrum_Ing) ProtoMessage() {}

func (x *Fulcrum_Ing) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulcrum_Ing.ProtoReflect.Descriptor instead.
func (*Fulcrum_Ing) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{7}
}

func (x *Fulcrum_Ing) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

type Ing_Broker_RenombrarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector      string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base        string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	NuevoNombre string `protobuf:"bytes,3,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`
}

func (x *Ing_Broker_RenombrarBase) Reset() {
	*x = Ing_Broker_RenombrarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Broker_RenombrarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Broker_RenombrarBase) ProtoMessage() {}

func (x *Ing_Broker_RenombrarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Broker_RenombrarBase.ProtoReflect.Descriptor instead.
func (*Ing_Broker_RenombrarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{8}
}

func (x *Ing_Broker_RenombrarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Broker_RenombrarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Broker_RenombrarBase) GetNuevoNombre() string {
	if x != nil {
		return x.NuevoNombre
	}
	return ""
}

type Ing_Fulcrum_RenombrarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector      string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base        string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	NuevoNombre string `protobuf:"bytes,3,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`
}

func (x *Ing_Fulcrum_RenombrarBase) Reset() {
	*x = Ing_Fulcrum_RenombrarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Fulcrum_RenombrarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Fulcrum_RenombrarBase) ProtoMessage() {}

func (x *Ing_Fulcrum_RenombrarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Fulcrum_RenombrarBase.ProtoReflect.Descriptor instead.
func (*Ing_Fulcrum_RenombrarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{9}
}

func (x *Ing_Fulcrum_RenombrarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Fulcrum_RenombrarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Fulcrum_RenombrarBase) GetNuevoNombre() string {
	if x != nil {
		return x.NuevoNombre
	}
	return ""
}

type Ing_Broker_ActualizarValor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector     string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base       string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	NuevoValor int32  `protobuf:"varint,3,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
}

func (x *Ing_Broker_ActualizarValor) Reset() {
	*x = Ing_Broker_ActualizarValor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Broker_ActualizarValor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Broker_ActualizarValor) ProtoMessage() {}

func (x *Ing_Broker_ActualizarValor) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Broker_ActualizarValor.ProtoReflect.Descriptor instead.
func (*Ing_Broker_ActualizarValor) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{10}
}

func (x *Ing_Broker_ActualizarValor) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Broker_ActualizarValor) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Broker_ActualizarValor) GetNuevoValor() int32 {
	if x != nil {
		return x.NuevoValor
	}
	return 0
}

type Ing_Fulcrum_ActualizarValor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector     string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base       string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	NuevoValor int32  `protobuf:"varint,3,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
}

func (x *Ing_Fulcrum_ActualizarValor) Reset() {
	*x = Ing_Fulcrum_ActualizarValor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Fulcrum_ActualizarValor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Fulcrum_ActualizarValor) ProtoMessage() {}

func (x *Ing_Fulcrum_ActualizarValor) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Fulcrum_ActualizarValor.ProtoReflect.Descriptor instead.
func (*Ing_Fulcrum_ActualizarValor) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{11}
}

func (x *Ing_Fulcrum_ActualizarValor) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Fulcrum_ActualizarValor) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ing_Fulcrum_ActualizarValor) GetNuevoValor() int32 {
	if x != nil {
		return x.NuevoValor
	}
	return 0
}

type Ing_Broker_BorrarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *Ing_Broker_BorrarBase) Reset() {
	*x = Ing_Broker_BorrarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Broker_BorrarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Broker_BorrarBase) ProtoMessage() {}

func (x *Ing_Broker_BorrarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Broker_BorrarBase.ProtoReflect.Descriptor instead.
func (*Ing_Broker_BorrarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{12}
}

func (x *Ing_Broker_BorrarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Broker_BorrarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type Ing_Fulcrum_BorrarBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *Ing_Fulcrum_BorrarBase) Reset() {
	*x = Ing_Fulcrum_BorrarBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lab5_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ing_Fulcrum_BorrarBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ing_Fulcrum_BorrarBase) ProtoMessage() {}

func (x *Ing_Fulcrum_BorrarBase) ProtoReflect() protoreflect.Message {
	mi := &file_lab5_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ing_Fulcrum_BorrarBase.ProtoReflect.Descriptor instead.
func (*Ing_Fulcrum_BorrarBase) Descriptor() ([]byte, []int) {
	return file_lab5_proto_rawDescGZIP(), []int{13}
}

func (x *Ing_Fulcrum_BorrarBase) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *Ing_Fulcrum_BorrarBase) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

var File_lab5_proto protoreflect.FileDescriptor

var file_lab5_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x61, 0x62, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x0b, 0x4b, 0x61, 0x69, 0x73, 0x5f, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22,
	0x2b, 0x0a, 0x0b, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x4b, 0x61, 0x69, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x0c,
	0x4b, 0x61, 0x69, 0x73, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x0c, 0x46, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x5f, 0x4b, 0x61, 0x69, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x74,
	0x5f, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x63, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x6c, 0x6f, 0x6a, 0x22, 0x5a, 0x0a, 0x16, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x5f, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22,
	0x2a, 0x0a, 0x0a, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x17, 0x49,
	0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x41, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x46, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x5f, 0x49, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x22, 0x69, 0x0a,
	0x18, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x65,
	0x76, 0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x6a, 0x0a, 0x19, 0x49, 0x6e, 0x67, 0x5f,
	0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61,
	0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x4e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x22, 0x69, 0x0a, 0x1a, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x5f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22,
	0x6a, 0x0a, 0x1b, 0x49, 0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x41,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75,
	0x65, 0x76, 0x6f, 0x5f, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x15, 0x49,
	0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72,
	0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x22, 0x44, 0x0a, 0x16, 0x49, 0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f,
	0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x32, 0x8a, 0x06, 0x0a, 0x0d, 0x4c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x5f, 0x35, 0x12, 0x49, 0x0a, 0x13, 0x41, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x72, 0x5f, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x5f, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x1a,
	0x12, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f,
	0x49, 0x6e, 0x67, 0x12, 0x4c, 0x0a, 0x14, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x5f, 0x42,
	0x61, 0x73, 0x65, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x1f, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d,
	0x5f, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x13, 0x2e, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x49, 0x6e,
	0x67, 0x12, 0x4d, 0x0a, 0x15, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x5f, 0x42,
	0x61, 0x73, 0x65, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x52,
	0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x12, 0x2e, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x67,
	0x12, 0x50, 0x0a, 0x16, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x5f, 0x42, 0x61,
	0x73, 0x65, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x21, 0x2e, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f,
	0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x13, 0x2e,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x49,
	0x6e, 0x67, 0x12, 0x51, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72,
	0x5f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x22, 0x2e,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x5f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f,
	0x72, 0x1a, 0x12, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x5f, 0x49, 0x6e, 0x67, 0x12, 0x54, 0x0a, 0x18, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x72, 0x5f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75,
	0x6d, 0x12, 0x23, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x46,
	0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x1a, 0x13, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x49, 0x6e, 0x67, 0x12, 0x47, 0x0a, 0x12, 0x42,
	0x6f, 0x72, 0x72, 0x61, 0x72, 0x5f, 0x42, 0x61, 0x73, 0x65, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65,
	0x1a, 0x12, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x5f, 0x49, 0x6e, 0x67, 0x12, 0x4a, 0x0a, 0x13, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x5f, 0x42,
	0x61, 0x73, 0x65, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x1e, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x67, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d,
	0x5f, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x13, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x49, 0x6e, 0x67,
	0x12, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x5f,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x4b, 0x61, 0x69, 0x73, 0x5f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x4b, 0x61, 0x69, 0x73,
	0x12, 0x41, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x5f,
	0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x14, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x4b, 0x61, 0x69, 0x73, 0x5f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x1a, 0x14, 0x2e,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x4b,
	0x61, 0x69, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lab5_proto_rawDescOnce sync.Once
	file_lab5_proto_rawDescData = file_lab5_proto_rawDesc
)

func file_lab5_proto_rawDescGZIP() []byte {
	file_lab5_proto_rawDescOnce.Do(func() {
		file_lab5_proto_rawDescData = protoimpl.X.CompressGZIP(file_lab5_proto_rawDescData)
	})
	return file_lab5_proto_rawDescData
}

var file_lab5_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lab5_proto_goTypes = []interface{}{
	(*Kais_Broker)(nil),                 // 0: broker.Kais_Broker
	(*Broker_Kais)(nil),                 // 1: broker.Broker_Kais
	(*Kais_Fulcrum)(nil),                // 2: broker.Kais_Fulcrum
	(*Fulcrum_Kais)(nil),                // 3: broker.Fulcrum_Kais
	(*Ing_Broker_AgregarBase)(nil),      // 4: broker.Ing_Broker_AgregarBase
	(*Broker_Ing)(nil),                  // 5: broker.Broker_Ing
	(*Ing_Fulcrum_AgregarBase)(nil),     // 6: broker.Ing_Fulcrum_AgregarBase
	(*Fulcrum_Ing)(nil),                 // 7: broker.Fulcrum_Ing
	(*Ing_Broker_RenombrarBase)(nil),    // 8: broker.Ing_Broker_RenombrarBase
	(*Ing_Fulcrum_RenombrarBase)(nil),   // 9: broker.Ing_Fulcrum_RenombrarBase
	(*Ing_Broker_ActualizarValor)(nil),  // 10: broker.Ing_Broker_ActualizarValor
	(*Ing_Fulcrum_ActualizarValor)(nil), // 11: broker.Ing_Fulcrum_ActualizarValor
	(*Ing_Broker_BorrarBase)(nil),       // 12: broker.Ing_Broker_BorrarBase
	(*Ing_Fulcrum_BorrarBase)(nil),      // 13: broker.Ing_Fulcrum_BorrarBase
}
var file_lab5_proto_depIdxs = []int32{
	4,  // 0: broker.Laboratorio_5.Agregar_Base_Broker:input_type -> broker.Ing_Broker_AgregarBase
	6,  // 1: broker.Laboratorio_5.Agregar_Base_Fulcrum:input_type -> broker.Ing_Fulcrum_AgregarBase
	8,  // 2: broker.Laboratorio_5.Renombrar_Base_Broker:input_type -> broker.Ing_Broker_RenombrarBase
	9,  // 3: broker.Laboratorio_5.Renombrar_Base_Fulcrum:input_type -> broker.Ing_Fulcrum_RenombrarBase
	10, // 4: broker.Laboratorio_5.Actualizar_Valor_Broker:input_type -> broker.Ing_Broker_ActualizarValor
	11, // 5: broker.Laboratorio_5.Actualizar_Valor_Fulcrum:input_type -> broker.Ing_Fulcrum_ActualizarValor
	12, // 6: broker.Laboratorio_5.Borrar_Base_Broker:input_type -> broker.Ing_Broker_BorrarBase
	13, // 7: broker.Laboratorio_5.Borrar_Base_Fulcrum:input_type -> broker.Ing_Fulcrum_BorrarBase
	0,  // 8: broker.Laboratorio_5.GetEnemigos_Broker:input_type -> broker.Kais_Broker
	2,  // 9: broker.Laboratorio_5.GetEnemigos_Fulcrum:input_type -> broker.Kais_Fulcrum
	5,  // 10: broker.Laboratorio_5.Agregar_Base_Broker:output_type -> broker.Broker_Ing
	7,  // 11: broker.Laboratorio_5.Agregar_Base_Fulcrum:output_type -> broker.Fulcrum_Ing
	5,  // 12: broker.Laboratorio_5.Renombrar_Base_Broker:output_type -> broker.Broker_Ing
	7,  // 13: broker.Laboratorio_5.Renombrar_Base_Fulcrum:output_type -> broker.Fulcrum_Ing
	5,  // 14: broker.Laboratorio_5.Actualizar_Valor_Broker:output_type -> broker.Broker_Ing
	7,  // 15: broker.Laboratorio_5.Actualizar_Valor_Fulcrum:output_type -> broker.Fulcrum_Ing
	5,  // 16: broker.Laboratorio_5.Borrar_Base_Broker:output_type -> broker.Broker_Ing
	7,  // 17: broker.Laboratorio_5.Borrar_Base_Fulcrum:output_type -> broker.Fulcrum_Ing
	1,  // 18: broker.Laboratorio_5.GetEnemigos_Broker:output_type -> broker.Broker_Kais
	3,  // 19: broker.Laboratorio_5.GetEnemigos_Fulcrum:output_type -> broker.Fulcrum_Kais
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_lab5_proto_init() }
func file_lab5_proto_init() {
	if File_lab5_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lab5_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kais_Broker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broker_Kais); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kais_Fulcrum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fulcrum_Kais); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Broker_AgregarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broker_Ing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Fulcrum_AgregarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fulcrum_Ing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Broker_RenombrarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Fulcrum_RenombrarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Broker_ActualizarValor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Fulcrum_ActualizarValor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Broker_BorrarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lab5_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ing_Fulcrum_BorrarBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lab5_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lab5_proto_goTypes,
		DependencyIndexes: file_lab5_proto_depIdxs,
		MessageInfos:      file_lab5_proto_msgTypes,
	}.Build()
	File_lab5_proto = out.File
	file_lab5_proto_rawDesc = nil
	file_lab5_proto_goTypes = nil
	file_lab5_proto_depIdxs = nil
}
